"""Common constants."""


__all__ = [
    'ERR_NO_SUCH_SERVER',
    'ERR_USER_ABORT',
    'ERR_CONNECTION_REFUSED',
    'ERR_CONNECTION_TIMEOUT',
    'ERR_REQUEST_ID_MISMATCH',
    'ERR_WRONG_PASSWORD',
    'LOG_FORMAT'
]


ERR_NO_SUCH_SERVER = 2
ERR_USER_ABORT = 3
ERR_CONNECTION_REFUSED = 4
ERR_CONNECTION_TIMEOUT = 5
ERR_REQUEST_ID_MISMATCH = 6
ERR_WRONG_PASSWORD = 7
LOG_FORMAT = '[%(levelname)s] %(name)s: %(message)s'
