"""Common erroneous return codes."""


__all__ = [
    'NO_SUCH_SERVER',
    'USER_ABORT',
    'CONNECTION_REFUSED',
    'CONNECTION_TIMEOUT',
    'REQUEST_ID_MISMATCH',
    'WRONG_PASSWORD'
]


NO_SUCH_SERVER = 2
USER_ABORT = 3
CONNECTION_REFUSED = 4
CONNECTION_TIMEOUT = 5
REQUEST_ID_MISMATCH = 6
WRONG_PASSWORD = 7
