#! /usr/bin/env python3
"""rconclt.

A Minecraft RCON client.

Usage:
    rconclt <server> datetime [--format=<format>] [options]
    rconclt <server> fortune [--long] [--offensive] [options]
    rconclt <server> <command> [<args>...] [options]

Options:
    --passwd=<passwd>   Specifies the respective RCON password.
    --format=<format>   Specifies the datetime format [default: %c].
    --long              Also generate long fortunes.
    --offensive         Only genenrate offensive fortunes.
    --debug             Enters debug mode.
    --help, -h          Shows this page.
"""
from logging import DEBUG, INFO, basicConfig, getLogger
from sys import exit as exit_

from docopt import docopt

from mcipc.rcon.client import Client
from mcipc.rcon.credentials import InvalidCredentialsError, Credentials


LOGGER = getLogger(__file__)
_LOG_FORMAT = '[%(levelname)s] %(name)s: %(message)s'


def main(options):
    """Runs the RCON client."""

    log_level = DEBUG if options['--debug'] else INFO
    basicConfig(level=log_level, format=_LOG_FORMAT)

    try:
        host, port, passwd = Credentials.from_string(options['<server>'])
    except InvalidCredentialsError as error:
        LOGGER.error(error)
        exit_(2)

    if passwd is None:
        passwd = options['--passwd'] or ''

    with Client(host, port) as client:
        if client.login(passwd):
            if options['datetime']:
                result = client.datetime(frmt=options['--format'])
            elif options['fortune']:
                result = client.fortune(
                    short=not options['--long'],
                    offensive=options['--offensive'])
            else:
                result = client.run(options['<command>'], *options['<args>'])

            if result:
                LOGGER.info(result)
        else:
            LOGGER.error('Failed to log in.')
            exit_(1)


if __name__ == '__main__':
    main(docopt(__doc__))
