#! /usr/bin/env python3
"""rconshell.

An interactive RCON shell.

Usage:
    rconshell [<server>] [options]

Options:
    --host=<host>, -H   Specifies the host.
    --port=<port>, -p   Specifies the port.
    --prompt=<prompt>   Specifies the shell prompt.
    --help, -h          Show this page.
"""
from logging import INFO, basicConfig, getLogger
from sys import exit, stderr    # pylint: disable=W0622

from mcipc.config import LOG_FORMAT
from mcipc.rcon.config import CONFIG
from mcipc.rcon.console import PS1, rconcmd


LOGGER = getLogger(__file__)


def main():
    """Runs the RCON shell."""

    try:
        from docopt import docopt
    except ModuleNotFoundError:
        print('docopt not installed. CLI not available.', file=stderr)
        exit(3)

    options = docopt(__doc__)
    basicConfig(level=INFO, format=LOG_FORMAT)
    server = options['<server>']
    host = None
    port = None
    passwd = None
    prompt = options['--prompt'] or PS1

    if server:
        try:
            host, port, passwd = CONFIG.servers[server]
        except KeyError:
            LOGGER.error('No such server: %s.', server)
            exit(4)

    host = options['--host'] or host
    port = int(options['--port'] or port)
    rconcmd(host, port, passwd, prompt)


if __name__ == '__main__':
    main()
