#! /usr/bin/env python3
"""rconshell.

An interactive RCON shell.

Usage:
    rconshell [<server>] [options]

Options:
    --host=<host>, -H   Specifies the host.
    --port=<port>, -p   Specifies the port.
    --prompt=<prompt>   Specifies the shell prompt.
    --help, -h          Show this page.
"""
from logging import INFO, basicConfig, getLogger
from sys import exit    # pylint: disable=W0622

from mcipc.config import LOG_FORMAT
from mcipc.rcon.config import CONFIG
from mcipc.rcon.console import PS1, rconcmd


LOGGER = getLogger(__file__)


def main():
    """Runs the RCON shell."""

    basicConfig(level=INFO, format=LOG_FORMAT)
    host = None
    port = None
    passwd = None
    prompt = PS1

    try:
        from docopt import docopt
    except ModuleNotFoundError:
        LOGGER.warning('Package docopt is not installed.')
        LOGGER.info('Argument parsing not available.')
    else:
        options = docopt(__doc__)
        server = options['<server>']
        prompt = options['--prompt'] or prompt

        if server:
            try:
                host, port, passwd = CONFIG.servers[server]
            except KeyError:
                LOGGER.error('No such server: %s.', server)
                exit(4)

        host = options['--host'] or host
        port = int(options['--port']) if options['--port'] else port

    exit_code = rconcmd(host, port, passwd, prompt)
    exit(exit_code)


if __name__ == '__main__':
    main()
