#! /usr/bin/env python3
"""Server wrapper test."""

from ipaddress import IPv4Address

from mcipc.srvwrap.wrapper import spawn


def main():
    """Runs the test script."""

    command = ('/usr/bin/java', '-jar', 'server.jar', 'nogui')
    host = IPv4Address('127.0.0.1')
    port = 5000
    cwd = '/home/rne/Downloads/minecraft_server'
    result = spawn(command, host, port, cwd=cwd)
    print(result)


if __name__ == '__main__':
    main()
